SELECT * FROM customer_behavior.customer;
SELECT * FROM customer LIMIT 5;
# Q1. Total revenue generated by female vs male customers?
select gender, SUM(purchase_amount) as revenue from customer group by gender;

#Q2. Which customers use purchase amount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer where discount_applied='Yes' and 
purchase_amount >= (select avg(purchase_amount) from customer);

#Q3. Which are the top 5 products with the highest average review ratings?
select item_purchased, round(avg(review_rating),1)as Average_product_rating
from customer group by item_purchased order by Average_product_rating desc LIMIT 5;

#Q4. Compare the average Purchase Amounts between Standard and Express shipping?
select shipping_type, Round(avg(purchase_amount),2) as Average_Purchase_Amount 
from customer where shipping_type in ('Express', 'Standard') group by shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?
select COUNT(customer_id) as Total_customers, subscription_status, Round(avg(purchase_amount),2) as Average_spend, 
Round(SUM(purchase_amount),2) as Total_Revenue from customer group by subscription_status order by Total_Revenue;	

#Q6. Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased , Round(100 * SUM(Case when discount_applied='Yes' then 1 else 0 END)/Count(*),2) as discount_rate
from customer group by item_purchased order by discount_rate desc LIMIT 5;

#Q7. Segment customers into New, Returning, Loyal based on their total number of previous purchases, 
# and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
Case when previous_purchases=1 then "New"
when previous_purchases between 2 and 10 then "Returning"
else "Loyal" END as customer_segment from customer)

select customer_segment, count(*) as Number_of_customers from customer_type group by customer_segment;

#Q8. What are the top 3 most purchased products in each category?
with item_counts as (
select category, item_purchased, 
COUNT(customer_id)as Total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank 
from customer group by category, item_purchased
)
select item_rank, item_purchased, Total_orders, category from item_counts
where item_rank<=3;

#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as Repeat_buyers from customer 
where previous_purchases > 5 group by subscription_status;

#Q10. What is the revenue contribution of each age group?
select Round(SUM(purchase_amount),2) AS Revenue, age_group from customer
group by age_group order by Revenue desc;